### ISSUE TITLE
Issue running vignette

### ISSUE THREAD

**Issue by owensgl** [deruncie/GridLMM#1]
I'm trying to run the vignette and I'm getting an error:

> > library(GridLMM)
> > vignette(topic = "Running_GridLMM_GWAS", package='GridLMM')
> Warning message:
> vignette ‘Running_GridLMM_GWAS’ not found 

The vignette is on the git repository, so I'm not sure what is going wrong.

**Comment by deruncie** [comment]
Try installing the package with: 

```
devtools::install_github('deruncie/GridLMM', build_vignettes = TRUE)
```

Let me know if that works.

**Comment by owensgl** [comment]
Trying that did not fix it. I get the same error.

**Comment by deruncie** [comment]
Try this:
```
devtools::install_github('deruncie/GridLMM', build_opts = c("--no-resave-data", "--no-manual"),force = TRUE)
```

**Comment by owensgl** [comment]
That worked! It brought up errors that I hadn't installed KRLS, qqman and snpStats. After installing those, it worked. The program seemed to install fine without those, but I guess that was the issue with the vignettes.

**Comment by deruncie** [comment]
Oh, yes. Those are only needed in the vignette. Thanks
