### ISSUE TITLE
Unexpected ')' in GridLMM_GWAS.R file

### ISSUE THREAD

**Issue by HaipengU** [deruncie/GridLMM#4]
Hi,
It seems like there is an extra ")" at line 264 which gave me trouble to install the package. Can you check this? 

Thanks,
Haipeng

**Comment by deruncie** [comment]
Thanks! Not sure how that got in there. Should be fixed, but let me know.

Dan

**Comment by HaipengU** [comment]
Thanks! I can install the package now. One more thing bout the build of the vignette, I can not build the vignette using build_opts argument in devtools since it seems silently ignore the errors (e.g., some packages used in vignette are not installed) during the creation of vignette.  I ended up building the vignette use the code 'remotes::install_github('deruncie/GridLMM',build_vignettes = TRUE)'. Hopefully this will help other users who may get similar issues. 

Thanks,
Haipeng
